import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "../src/Link";
import { useRouter } from "next/router";
import {
  Grid,
  Box,
  Typography,
  Button,
  Rating,
  Divider,
  List,
  ListSubheader,
  ListItem,
  ListItemText,
  ListItemButton,
  Collapse,
  ListItemIcon,
  styled,
  Avatar,
} from "@mui/material";

import LinearProgress, {
  linearProgressClasses,
} from "@mui/material/LinearProgress";

import {
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
  Https as HttpsIcon,
  AccountBalanceWallet as AccountBalanceWalletIcon,
  Replay as ReplayIcon,
  DeliveryDining as DeliveryDiningIcon,
  Security as SecurityIcon,
  EmailOutlined as EmailOutlinedIcon,
  Facebook as FacebookIcon,
  Twitter as TwitterIcon,
  Instagram as InstagramIcon,
} from "@mui/icons-material";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const handleStart = (url) => {
      // console.log(`Loading: ${url}`);
      console.time("loading time");
      setLoading(true);
    };
    const handleStop = () => {
      console.timeEnd("loading time");
      setLoading(false);
    };

    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleStop);
    router.events.on("routeChangeError", handleStop);

    return () => {
      router.events.off("routeChangeStart", handleStart);
      router.events.off("routeChangeComplete", handleStop);
      router.events.off("routeChangeError", handleStop);
    };
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading && <h1>Loading ...</h1>}
      <main className={styles.main}>
        <h2 className={styles.title}>
          <Link href="/product/61713734d9b1aaab750d74b4">/product</Link>
          <ExpandMoreIcon />
        </h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
